name: upload

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - run: echo 'Hello, world!' > file.txt

     - name: Print branch name
        run: |
          # `github.ref` からブランチ名を取得
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Current branch: $BRANCH_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-artifact
          path: file.txt
          retention-days: 14
