name: upload

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - run: echo 'Hello, world!' > file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-artifact
          path: file.txt
          retention-days: 14

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: upload-artifact
          path: ~/artifacts

      - run: cat ~/artifacts/file.txt
